name: Coolblue Seconde Chance Tracker

on:
  schedule:
    # S'exécute toutes les heures (vous pouvez ajuster, ex: '*/30 * * * *' pour toutes les 30 min)
    - cron: '*/10 * * * *'
  workflow_dispatch: # Permet de lancer le script manuellement depuis l'onglet Actions de GitHub

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Lancer le script de vérification
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: node tracker.js
